version: '3'
services:
  ship-postgres:
    container_name: postgres
    build:
        dockerfile: Dockerfile
        context: ./postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/conf/postgresql.conf:/tmp/postgresql.conf
      - ./postgres/${POSTGRES_VOLUME}:/var/lib/postgresql/data/pgdata
  ship-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - ship-postgres
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  graphql-engine:
    image: hasura/graphql-engine
    container_name: hasura
    ports:
    - "${HASURA_PORT}:8080"
    depends_on:
    - ship-postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"
  parser:
    container_name: parser
    build:
        dockerfile: Dockerfile
        context: ./
